DROP TABLE IF EXISTS Compte;
DROP TABLE IF EXISTS Taille;
DROP TABLE IF EXISTS Chaussure;
DROP TABLE IF EXISTS Couleur;
DROP TABLE IF EXISTS Prix;
DROP TABLE IF EXISTS Marque;
DROP TABLE IF EXISTS Disponibilite;

CREATE TABLE Compte (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    pseudo VARCHAR(20) NOT NULL,
    mdp VARCHAR(20) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE Chaussure (
    idChaussure INTEGER PRIMARY KEY AUTOINCREMENT,
    nom VARCHAR(20) NOT NULL
);

CREATE TABLE Couleur (
    idCouleur INTEGER PRIMARY KEY,
    nomCouleur VARCHAR(20) NOT NULL
);

CREATE TABLE Taille (
    idTaille INTEGER PRIMARY KEY AUTOINCREMENT,
    valeurTaille VARCHAR(50) NOT NULL
);

CREATE TABLE Prix (
    idPrix INTEGER PRIMARY KEY AUTOINCREMENT,
    prix INT NOT NULL
);

CREATE TABLE Marque (
    idMarque INTEGER PRIMARY KEY AUTOINCREMENT,
    marque VARCHAR(20) NOT NULL
);

CREATE TABLE Disponibilite (
    idChaussure INTEGER,
    idCouleur INTEGER,
    idTaille INTEGER,
    idPrix INTEGER,
    idMarque INTEGER,
    FOREIGN KEY (idChaussure) REFERENCES Chaussure(idChaussure) ON DELETE CASCADE
    FOREIGN KEY (idCouleur) REFERENCES Couleur(idCouleur) ON DELETE CASCADE
    FOREIGN KEY (idTaille) REFERENCES Taille(idTaille) ON DELETE CASCADE
    FOREIGN KEY (idPrix) REFERENCES Prix(idPrix) ON DELETE CASCADE
    FOREIGN KEY (idMarque) REFERENCES Marque(idMarque) ON DELETE CASCADE
);